# Generated by Django 5.0.6 on 2024-05-16 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTarjeta', models.CharField(max_length=30)),
                ('dataCad', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comandes.comanda')),
            ],
        ),
    ]
