# Generated by Django 5.0.6 on 2024-05-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0001_initial'),
        ('pagament', '0003_pagament_actiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagament',
            name='client',
        ),
        migrations.AlterField(
            model_name='pagament',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandes.comanda'),
        ),
    ]
