# Generated by Django 5.0.6 on 2024-05-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0001_initial'),
        ('pagament', '0004_remove_pagament_client_alter_pagament_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagament',
            name='comanda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comandes.comanda'),
        ),
    ]
